### ISSUE TITLE
Level-party upgrade for Node 11+ ?

### ISSUE THREAD

**Issue by MongoExpUser** [Level/party#18] opened 2019-04-10 03:49 UTC
This module is too useful to be left unattended. It needs to be updated for Node 11+.

Anyone knows any future plan for this module?

I have not found any module as **easy** and **useful** as this for multiple processes/**clusters** LevelDB connections.

**Comment by vweevers** [comment] 2019-12-08 16:11
Duplicate of #17 (which is about to be closed too).

**Closed by vweevers** 2019-12-08 16:11 UTC
